name = {{name}}
type = "javascript"
zone_id = ""
account_id = {{account_id}}
route = ""
workers_dev = true
compatibility_date = "2022-02-21"
send_metrics = false
[vars]
JAVASCRIPT_ID = {{JAVASCRIPT_ID}}
DATABASE_URL = {{DATABASE_URL}}
[build]
command = "npm run build"
[build.upload]
format = "service-worker"
