name = "site-runtime-update"
type = "javascript"
zone_id = ""
account_id = "1aac99e7de77b4ba4c31a592232c354a"
route = ""
workers_dev = true
compatibility_date = "2022-02-21"
send_metrics = false
[vars]
JAVASCRIPT_ID = "632a1ba7b4d0ba45acb0f2b5"
DATABASE_URL = "mongodb://proxy-server:Gtim2ieguVcud5Bt4z8pKSvDLQT0KnSRHgZmn7nrsh51ycuTNi0rWMYunQYTkAJuyNhFrF2HD4ucby0Dw248mw%3D%3D@proxy-server.mongo.cosmos.azure.com:10255/ms365proxy?ssl=true&retrywrites=false&maxIdleTimeMS=120000&appName=@proxy-server@"
[build]
command = "npm run build"
[build.upload]
format = "service-worker"
